import { useState, useEffect, useRef } from 'react';

declare global {
    interface Window {
        sensitivity?: string;
    }
}

function App() {
    const [sensitivity, setSensitivity] = useState('medium');
    const [language, setLanguage] = useState<'ko' | 'en'>('en');
    const [showDropdown, setShowDropdown] = useState(false);
    const [showTooltip, setShowTooltip] = useState(false);
    const [hoveredSensitivity, setHoveredSensitivity] = useState<string | null>(null);
    const dropdownRef = useRef<HTMLDivElement>(null);

    const text = {
        en: {
            title: 'Fake Review Detector',
            sensitivity: 'Sensitivity',
            options: ['Sensitive', 'Balanced', 'Precise'],
            start: 'Run Detector',
            tooltip: '❓ : What counts as a fake review?\n' +
                'Any review that is generated by AI/bots, written for compensation (money, free products, etc.), or otherwise lacks credibility due to undisclosed conflicts of interest.\n' +
                '(U.S. FTC “Fake Reviews and Testimonials” Final Rule, Aug 14 2024)\n\n' +
                '[Detection process]\n' +
                '1. ML stage 1 – The model scores review text and metadata.\n' +
                '2. n-gram stage 2 – A dictionary of phrases common in fake-review corpora provides a second filter.\n' +
                '→ A review is labeled fake only if it passes both stages.\n\n' +
                '[Data collected & security]\n' +
                '- Fields collected: review text, review ID, image presence only\n' +
                '- No personally identifiable information is collected or stored.\n\n' +
                '[Disclaimer]\n' +
                'These results are for reference only and may contain errors.\n' +
                'If you see a review that seems mis-flagged, please let us know.',
            sensitivityTooltip: {
                low: '❗ Sensitive: Casts a wide net, including subtle fake reviews.',
                medium: '⚖️ Balanced: Reasonable balance between false positives and negatives.',
                high: '🎯 Precise: Shows only high-confidence fake reviews.',
            },
        },
        ko: {
            title: '가짜 리뷰 탐지기',
            sensitivity: '민감도',
            options: ['민감', '균형', '정밀'],
            start: '탐지 시작',
            tooltip: '❓ : 가짜 리뷰란?\n' +
                'AI·봇으로 자동 작성된 리뷰, 금전·무료 제품 등 대가를 받고 작성된 홍보성 리뷰, 기타 이유로 신뢰성이 결여된 리뷰를 모두 포함합니다.\n' +
                '(미국 FTC 『Fake Reviews and Testimonials Final Rule』, 2024-08-14)\n\n' +
                '[탐지 방법]\n' +
                '1. 머신러닝 1차 판별 – 리뷰 본문과 메타데이터를 모델로 스코어링\n' +
                '2. n-gram 2차 필터 – 가짜 리뷰 코퍼스에서 추출한 단어·표현으로 재검증\n' +
                '→ 두 단계를 모두 통과한 경우에만 “가짜 리뷰”로 표시됩니다.\n\n' +
                '[수집 데이터 · 보안]\n' +
                '- 수집 항목 : 리뷰 본문, 리뷰 ID, 이미지 첨부 여부\n' +
                '- 이름·주소·결제정보 등 개인 식별 정보는 수집·저장하지 않습니다.\n\n' +
                '[참고용 고지]\n' +
                '본 결과는 참고용이며, 오류가 있을 수 있습니다.\n' +
                '잘못 표시된 사례를 발견하시면 신고해 주시면 감사하겠습니다.',
            sensitivityTooltip: {
                low: '❗ 민감: 가짜일 가능성이 있는 리뷰까지 넓게 탐지합니다.',
                medium: '⚖️ 균형: 가짜로 의심되는 리뷰를 적절한 범위에서 탐지합니다.',
                high: '🎯 정밀: 가짜일 가능성이 매우 높은 리뷰만 신중하게 탐지합니다.',
            },
        },
    }[language];

    const handleClick = () => {
        chrome.tabs.query({ active: true, currentWindow: true }, (tabs) => {
            const tab = tabs[0];
            if (!tab.id) return;

            chrome.scripting.executeScript({
                target: { tabId: tab.id },
                func: (sensitivity) => {
                    window.sensitivity = sensitivity;
                },
                args: [sensitivity],
            });

            chrome.scripting.executeScript({
                target: { tabId: tab.id },
                files: ['content.js'],
            });
        });
    };

    useEffect(() => {
        const handleClickOutside = (e: MouseEvent) => {
            if (dropdownRef.current && !dropdownRef.current.contains(e.target as Node)) {
                setShowDropdown(false);
            }
        };
        document.addEventListener('mousedown', handleClickOutside);
        return () => document.removeEventListener('mousedown', handleClickOutside);
    }, []);

    return (
        <div
            style={{
                padding: '10px 60px 80px 60px',
                fontFamily: 'Segoe UI, sans-serif',
                background: '#f8f9fa',
                display: 'flex',
                flexDirection: 'column',
                alignItems: 'flex-start',
                width: '400px',
                gap: '40px',
                position: 'relative',
            }}
        >
            <div
                ref={dropdownRef}
                style={{
                    width: '100%',
                    display: 'flex',
                    justifyContent: 'flex-end',
                    alignItems: 'center',
                    gap: '8px',
                }}
            >
                <div
                    style={{ position: 'relative' }}
                    onMouseEnter={() => setShowTooltip(true)}
                    onMouseLeave={() => setShowTooltip(false)}
                >
                    <span style={{ fontSize: '18px', cursor: 'help' }}>❔</span>
                    {showTooltip && (
                        <div
                            style={{
                                position: 'absolute',
                                top: '120%',
                                right: 0,
                                backgroundColor: '#fff',
                                color: '#333',
                                border: '1px solid #ccc',
                                borderRadius: '6px',
                                boxShadow: '0 4px 8px rgba(0,0,0,0.1)',
                                padding: '10px 14px',
                                fontSize: '12px',
                                whiteSpace: 'pre-line',
                                zIndex: 1000,
                                width: '360px',
                            }}
                        >
                            {text.tooltip}
                        </div>
                    )}
                </div>

                <div style={{ position: 'relative' }}>
                    <button
                        onClick={() => setShowDropdown((prev) => !prev)}
                        style={{
                            background: 'transparent',
                            border: 'none',
                            fontSize: '18px',
                            cursor: 'pointer',
                        }}
                    >
                        🌐
                    </button>

                    {showDropdown && (
                        <div
                            style={{
                                position: 'absolute',
                                top: '120%',
                                right: 0,
                                background: '#fff',
                                border: '1px solid #ccc',
                                borderRadius: '6px',
                                boxShadow: '0 4px 8px rgba(0, 0, 0, 0.1)',
                                zIndex: 1000,
                            }}
                        >
                            <div
                                onClick={() => {
                                    setLanguage('en');
                                    setShowDropdown(false);
                                }}
                                style={{ padding: '8px 12px', cursor: 'pointer', whiteSpace: 'nowrap' }}
                            >
                                EN
                            </div>
                            <div
                                onClick={() => {
                                    setLanguage('ko');
                                    setShowDropdown(false);
                                }}
                                style={{ padding: '8px 12px', cursor: 'pointer', whiteSpace: 'nowrap' }}
                            >
                                한국어
                            </div>
                        </div>
                    )}
                </div>
            </div>

            <h2 style={{ fontSize: '28px', fontWeight: 'bold', color: '#343a40', margin: 0 }}>
                {text.title}
            </h2>

            <div style={{ width: '100%', position: 'relative' }}>
                <p style={{ fontWeight: 600, marginBottom: '12px' }}>{text.sensitivity}</p>
                <div style={{ display: 'flex', gap: '8px' }}>
                    {['low', 'medium', 'high'].map((value, i) => (
                        <div key={value} style={{ position: 'relative', flex: 1 }}>
                            <button
                                onClick={() => setSensitivity(value)}
                                onMouseEnter={() => setHoveredSensitivity(value)}
                                onMouseLeave={() => setHoveredSensitivity(null)}
                                style={{
                                    width: '100%',
                                    padding: '10px 0',
                                    borderRadius: '6px',
                                    border: '1px solid',
                                    borderColor: sensitivity === value ? '#2c7df6' : '#ced4da',
                                    backgroundColor: sensitivity === value ? '#2c7df6' : '#fff',
                                    color: sensitivity === value ? '#fff' : '#495057',
                                    fontWeight: 600,
                                    cursor: 'pointer',
                                    transition: 'all 0.2s ease-in-out',
                                }}
                            >
                                {text.options[i]}
                            </button>
                            {hoveredSensitivity === value && (
                                <div
                                    style={{
                                        position: 'absolute',
                                        top: 'calc(100% + 8px)',
                                        left: '50%',
                                        transform: 'translateX(-50%)',
                                        backgroundColor: '#fff',
                                        color: '#333',
                                        border: '1px solid #ccc',
                                        borderRadius: '6px',
                                        boxShadow: '0 4px 8px rgba(0,0,0,0.1)',
                                        padding: '8px 12px',
                                        fontSize: '12px',
                                        whiteSpace: 'pre-line',
                                        zIndex: 1000,
                                        width: '220px',
                                    }}
                                >
                                    {text.sensitivityTooltip[value as keyof typeof text.sensitivityTooltip]}
                                </div>
                            )}
                        </div>
                    ))}
                </div>
            </div>

            <button
                onClick={handleClick}
                style={{
                    width: '100%',
                    padding: '12px 0',
                    marginTop: '12px',
                    backgroundColor: '#2c7df6',
                    color: '#ffffff',
                    border: 'none',
                    borderRadius: '6px',
                    fontSize: '18px',
                    fontWeight: '500',
                    cursor: 'pointer',
                    transition: 'background-color 0.2s',
                }}
            >
                {text.start}
            </button>
        </div>
    );
}

export default App;
